command_timeout = 100

[directory]
truncation_length = 8
truncate_to_repo = false
style = "bold blue"
repo_root_style = "bold purple"
use_logical_path = false

[docker_context]
disabled = true

[gcloud]
disabled = true

[git_status]
format = "([${ahead_behind}${all_status}]($style) )"
style = "bold purple"
ignore_submodules = true
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
untracked = "[?${count}](black)"
stashed = '[\$${count}](blue)'
modified = "[!${count}](yellow)"
staged = "[+${count}](green)"
renamed = "[»${count}](green)"
deleted = "[x${count}](red)"

[direnv]
disabled = false
detect_files = [".envrc", ".env"]
